apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller
  name: alb-ingress-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alb-ingress-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alb-ingress-controller
    spec:
      containers:
      - name: alb-ingress-controller
        args:
          - --ingress-class=alb
          - --cluster-name=spcluster
          - --aws-vpc-id=vpc-055d412181ca47fac
          - --aws-region=ap-northeast-2
          - --aws-max-retries=10
        env:
          - name: AWS_ACCESS_KEY_ID
            value: AKIAWRVDFTCFSNDMG3PK
          - name: AWS_SECRET_ACCESS_KEY
            value: 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
        image: docker.io/amazon/aws-alb-ingress-controller:v1.1.9
      serviceAccountName: alb-ingress-controller
