---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-dp
  namespace: spspace
  labels:
    app: wp  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
      - name: wordpress
        image: wordpress
        resources:
          requests:
            cpu: "5m"
            memory: "10M"
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wpconfig
              key: host
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: wpconfig
              key: dbname
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: wpconfig
              key: dbuser
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: wpconfig
              key: dbpasswd
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
          - mountPath: /var/www/html
            name: wp-content
      volumes:
      - name: wp-content
        persistentVolumeClaim:
          claimName: wp-pvc        